export const TEAM = [
    { 
        firstName: 'Aaron',
        lastName: 'Miller',
        src: 'Aaron-Miller.jpg',
        title: '',
    },
    { 
        firstName: 'Abby',
        lastName: 'Houston',
        src: 'Abby-Houston.jpg',
        title: '',
    },
    { 
        firstName: 'Adam',
        lastName: 'Baumgardner',
        src: 'Adam-Baumgardner.jpg',
        title: '',
    },
    { 
        firstName: 'Adam',
        lastName: 'Kurstin',
        src: 'Adam-Kurstin.jpg',
        title: '',
    },
    { 
        firstName: 'Alejandro',
        lastName: 'Porras',
        src: 'Alejandro-Porras.jpg',
        title: '',
    },
    { 
        firstName: 'Alex',
        lastName: 'Caffee',
        src: 'Alex-Caffee.jpg',
        title: '',
    },
    { 
        firstName: 'Ali',
        lastName: 'Trachta',
        src: 'Ali-Trachta.jpg',
        title: '',
    },
    { 
        firstName: 'April',
        lastName: 'Kaminsky',
        src: 'April-Kaminsky.jpg',
        title: '',
    },
    { 
        firstName: 'Austin',
        lastName: 'Orth',
        src: 'Austin-Orth.png',
        title: '',
    },
    { 
        firstName: 'Benjamin',
        lastName: 'Michaux',
        src: 'Benjamin-Michaux.png',
        title: '',
    },
    { 
        firstName: 'Bethany',
        lastName: 'Culley',
        src: 'Bethany-Culley.jpg',
        title: '',
    },
    { 
        firstName: 'Brendan',
        lastName: 'Murray',
        src: 'Brendan-Murray.png',
        title: '',
    },
    { 
        firstName: 'Chrissy',
        lastName: 'Liberati',
        src: 'Chrissy-Liberati.jpg',
        title: '',
    },
    { 
        firstName: 'Courtney',
        lastName: 'Thomas',
        src: 'Courtney-Thomas.jpg',
        title: '',
    },
    { 
        firstName: 'Daniel',
        lastName: 'King',
        src: 'Daniel-King.jpg',
        title: '',
    },
    { 
        firstName: 'Daniel',
        lastName: 'Salmon',
        src: 'Daniel-Salmon.jpg',
        title: '',
    },
    { 
        firstName: 'Dave',
        lastName: 'Koegler',
        src: 'Dave-Koegler.jpg',
        title: '',
    },
    { 
        firstName: 'Elsa',
        lastName: 'Heffernan',
        src: 'Elsa-Heffernan.jpg',
        title: '',
    },
    { 
        firstName: 'Emily',
        lastName: 'Russell',
        src: 'Emily-Russell.jpg',
        title: '',
    },
    { 
        firstName: 'Emily',
        lastName: 'Seibel',
        src: 'Emily-Seibel.jpg',
        title: '',
    },
    { 
        firstName: 'Eva',
        lastName: 'Morrison',
        src: 'Eva-Morrison.jpg',
        title: '',
    },
    { 
        firstName: 'Geoff',
        lastName: 'Misek',
        src: 'Geoff-Misek.jpg',
        title: '',
    },
    { 
        firstName: 'Jacki',
        lastName: 'Anderson',
        src: 'Jacki-Anderson.png',
        title: '',
    },
    { 
        firstName: 'Jennie',
        lastName: 'Johnson',
        src: 'Jennie-Johnson.png',
        title: '',
    },
    { 
        firstName: 'Jess',
        lastName: 'Hair',
        src: 'Jess-Hair.png',
        title: '',
    },
    { 
        firstName: 'Joe',
        lastName: 'McLaughlin',
        src: 'Joe-McLaughlin.jpg',
        title: '',
    },
    { 
        firstName: 'Joe',
        lastName: 'Szescila',
        src: 'Joe-Szescila.jpg',
        title: '',
    },
    { 
        firstName: 'Joel',
        lastName: 'Griffith',
        src: 'Joel-Griffith.jpg',
        title: '',
    },
    { 
        firstName: 'Jonathan',
        lastName: 'Martin',
        src: 'Jonathan-Martin.jpg',
        title: '',
    },
    { 
        firstName: 'Jordan',
        lastName: 'Bazzani',
        src: 'Jordan-Bazzani.jpg',
        title: '',
    },
    { 
        firstName: 'Josh',
        lastName: 'Smith',
        src: 'Josh-Smith.jpg',
        title: '',
    },
    { 
        firstName: 'Juan',
        lastName: 'Angel Rojas',
        src: 'Juan-Angel-Rojas.jpg',
        title: '',
    },
    { 
        firstName: 'Karisa',
        lastName: 'Fernandez',
        src: 'Karisa-Fernandez.jpg',
        title: '',
    },
    { 
        firstName: 'Kelly',
        lastName: 'Munié',
        src: 'Kelly-Munie.jpg',
        title: '',
    },
    { 
        firstName: 'Kim',
        lastName: 'Cooperrider',
        src: 'Kim-Cooperrider.png',
        title: '',
    },
    { 
        firstName: 'Kyla',
        lastName: 'Kemmerer',
        src: 'Kyla-Kemmerer.jpg',
        title: '',
    },
    { 
        firstName: 'Laura',
        lastName: 'Fetch',
        src: 'Laura-Fetch.jpg',
        title: '',
    },
    { 
        firstName: 'Lilly',
        lastName: 'Madrid',
        src: 'Lilly-Madrid.jpg',
        title: '',
    },
    { 
        firstName: 'Liz',
        lastName: 'Pantalone',
        src: 'Liz-Pantalone.png',
        title: '',
    },
    { 
        firstName: 'Luke',
        lastName: 'Skurman',
        src: 'Luke-Skurman.jpg',
        title: '',
    },
    { 
        firstName: 'Maggie',
        lastName: 'Kohlhas',
        src: 'Maggie-Kohlhas.jpg',
        title: '',
    },
    { 
        firstName: 'Mark',
        lastName: 'Eshelman',
        src: 'Mark-Eshelman.png',
        title: '',
    },
    { 
        firstName: 'Mark',
        lastName: 'Tressler',
        src: 'Mark-Tressler.jpg',
        title: '',
    },
    { 
        firstName: 'Matt',
        lastName: 'Dolan',
        src: 'Matt-Dolan.jpg',
        title: '',
    },
    { 
        firstName: 'Melissa',
        lastName: 'Burnfield',
        src: 'Melissa-Burnfield.jpg',
        title: '',
    },
    { 
        firstName: 'Melissa',
        lastName: 'Wang',
        src: 'Melissa-Wang.jpg',
        title: '',
    },
    { 
        firstName: 'Michael',
        lastName: 'Scotto',
        src: 'Michael-Scotto.jpg',
        title: '',
    },
    { 
        firstName: 'Mitchell',
        lastName: 'Briner',
        src: 'Mitchell-Briner.jpg',
        title: '',
    },
    { 
        firstName: 'Nate',
        lastName: 'Bridi',
        src: 'Nate-Bridi.jpg',
        title: '',
    },
    { 
        firstName: 'Nate',
        lastName: 'Cochran',
        src: 'Nate-Cochran.jpg',
        title: '',
    },
    { 
        firstName: 'Nick',
        lastName: 'Dulac',
        src: 'Nick-Dulac.jpg',
        title: '',
    },
    { 
        firstName: 'Nolly',
        lastName: 'Gibbs',
        src: 'Nolly-Gibbs.jpg',
        title: '',
    },
    { 
        firstName: 'Omid',
        lastName: 'Gohari',
        src: 'Omid-Gohari.jpg',
        title: '',
    },
    { 
        firstName: 'Rebecca',
        lastName: 'Dilla',
        src: 'Rebecca-Dilla.jpg',
        title: '',
    },
    { 
        firstName: 'Ryan',
        lastName: 'Bell',
        src: 'Ryan-Bell.jpg',
        title: '',
    },
    { 
        firstName: 'Sabrina',
        lastName: 'Aravena',
        src: 'Sabrina-Aravena.jpg',
        title: '',
    },
    { 
        firstName: 'Sarah',
        lastName: 'Gremba',
        src: 'Sarah-Gremba.jpg',
        title: '',
    },
    { 
        firstName: 'Sarah',
        lastName: 'Wissinger',
        src: 'Sarah-Wissinger.jpg',
        title: '',
    },
    { 
        firstName: 'Shawn',
        lastName: 'Rancatore',
        src: 'Shawn-Rancatore.jpg',
        title: '',
    },
    { 
        firstName: 'Spencer',
        lastName: 'Kingman',
        src: 'Spencer-Kingman.jpg',
        title: '',
    },
    { 
        firstName: 'Stella',
        lastName: 'Chung',
        src: 'Stella-Chung.jpg',
        title: '',
    },
    { 
        firstName: 'Victoria',
        lastName: 'Zhang',
        src: 'Victoria-Zhang.jpg',
        title: '',
    },
    { 
        firstName: 'Vivan',
        lastName: 'Shah',
        src: 'Vivan-Shah.jpg',
        title: '',
    },
    { 
        firstName: 'Zach',
        lastName: 'Romitz',
        src: 'Zach-Romitz.jpg',
        title: '',
    },
    { 
        firstName: 'Zachary',
        lastName: 'Ettensohn',
        src: 'Zachary-Ettensohn.jpg',
        title: '',
    },
]
